---
 - name: template
   hosts: all 
   become: True

   tasks:
     - name: update 
       apt:
          update_cache: yes

     - name: Install NGINX Packages
       apt:
         name: nginx
         state: latest

     - name: Start Service
       service:
          name: nginx
          state: restarted
          enabled: yes

     - name: unzip
       apt:
          name: unzip
          state: latest    

     - name: Download 
       ansible.builtin.get_url:
         url: https://www.free-css.com/assets/files/free-css-templates/download/page283/moto.zip 
         dest: /home/ubuntu/

     - name: Extract 
       ansible.builtin.unarchive:
          src: moto.zip
          dest: /var/www/html/   
...
       
   
